### ISSUE TITLE
How about referring to my implementation?

### ISSUE THREAD

**Issue by kanryu** [Skycoder42/QtApng#1]
Hi,

Your apng plugin has been modified and used as part of QuickViewer.

As I am satisfied with my modifications, it will already be older than your implementation.

I read a bit of your latest implementation, but I decided to inform you about something better to say about 2 points.

1. Your apng format check contains unnecessary processing and is inefficient
     - ApngImageHandler::option(QImageIOHandler::Animation)
     - We only need to search for png signatures and acTL chunks, and then shouldn't do anything else.
     - Since the apng plugin contains inefficient and unnecessary operations to open a normal png image, when it is confirmed that there is no animation, it is necessary to switch to the usual png ImageIOHandler.
1. Your private class implementation is not a Qt standard implementation.
     - Declare a class with 'ApngImageHandlerPrivate' etc. followed by 'Private' in the header file and write a pointer with the variable name of 'd' in the private variable.
     - The private class is synchronized with the lifetime of the class of the main body, it should be new in the constructor and deleted in the destructor.
     - When inheriting from QImageIOHandler, it is necessary to check the file format with the options () method, but unnecessary const constraints are attached due to mistakes in the design of Qt, and it is impossible to avoid the workaround by private class.

The above is just my opinion, so you do not have to follow it.
I will open up my current implementation so please refer to it.

https://github.com/kanryu/qapng_Skycoder42

**Comment by Skycoder42** [comment]
Hi,

regarding your first point:
Yes, I get your idea, but I'm not shure if switching to the default png handler is possible inside the plugin. as it is not exposed as public symbol in the library. The reading performance could be improved, yes, but only if you are only interested in the `QImageIOHandler::Animation` option. For other options, it may be neccessary to read all metadata first.

I do understand your point, and only reading to acTL for the animated property wouldn't be to much effort, so I'll keep it in mind.

I am familiar with the pimpl design, and have used it for other Qt project, but as this plugin was originally not intended to be "released", I did not follow any guidlines. For now my goal was to release something, code cleanup, including this, is planned for a future release. but as there are no public headers in a plugin, there is not requirement because of binary compability, as for normal libraries.

Thanks for your suggestions.

**Comment by Skycoder42** [comment]
I finally came to clean up the project. Regarding your points as final reply:

I agree that checking for apng could be done faster, but the current implementation does do chunk parsing from my code anymore. Instead the libpng functions are used, which leads to much cleaner and more readable (and more reliable) code. Trying to read only until acTL is possible, but would basically "butcher" the current code, as all the "info" structs are read in one go via a single library function - and at least for now I am not willing to sacrifice this just to read a few bytes less.

regarding your second point: I renamed the header to be private headers. There is no public API, so no private implementation is needed. Also, the `ApngReader` class more or less takes that role. And due to the way I implemented the `canRead`, there is no problem with the const modifier anymore.

If you still have improvements, you can always create a pull request to incorporate your changes or file new issues.
