### ISSUE TITLE
Missing installation for Qt 5.11.3

### ISSUE THREAD

**Issue by OmniTroid** [Skycoder42/QtApng#6]
In https://install.skycoder42.de/qtmodules/mac_x64/ the installation target for Qt 5.11.3 is missing (would be named qt5113 I reckon)

**Comment by Skycoder42** [comment]
That is correct. Because of the quick release of 5.12.0 a few days after 5.11.3 I skipped over that one (As I generelly only provide the latest release and LTS-Release as CI-Builds).

I would recommend you update to 5.12 or build the module yourself, following the instructions from the readme - or you can fork the repository and trigger the CI-builds yourself. If you need any further help regarding the build process, feel free to ask.
